package jpa_exercise.model;

import javax.naming.Name;
import javax.persistence.*;

//TODO make the Address entity
//TODO map this class to table named ADDRESSES_EX
//TODO make the id field autogenerated from the database
//TODO map street to street_number column
@Entity
@Table(name="ADDRESSES_EX")
public class Address {

    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(name = "STREET_NUMBER")
    private String street;

    private int number;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }
}
