package jpa_exercise.model;

import java.time.LocalDate;
import java.util.List;

//TODO make the order entity
//TODO map this class to table named ORDERS_EX
//TODO make the id field autogenerated from the database
//TODO make the relationship with the products
//TODO make the relationship with the address
//TODO map orderDate to order_date column
public class Order {

    List<Product> products;
    private Integer id;
    private LocalDate orderDate;
    private Double price;
    private Address address;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDate getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(LocalDate orderDate) {
        this.orderDate = orderDate;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public List<Product> getProducts() {
        return products;
    }

    public void setProducts(List<Product> products) {
        this.products = products;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }
}
