package jpa_exercise.model;


//TODO make the product entity
//TODO map this class to table named PRODUCTS_EX
//TODO make the id field autogenerated from the database
public class Product {

    private Integer id;
    private String name;
    private String description;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
